import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { NewsletterFooter, Navigation, ThemeProvider} from "@/components";

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mindware - Comércio & Serviços",
  description: "Generated by create next app",
  icons: {
    icon: "/icon_white.ico",
  }
};

const navigationItems = [
    { name: "Início", link: "/#hero" },
    { name: "Sobre", link: "/#about" },
    { name: "Serviços", link: "/#services" },
    { name: "Testemunhas", link: "/#testimonials" },
    { name: "FAQs", link: "/#faqs" },
  ];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakarta.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Navigation
          items={navigationItems}
          showCTA={true}
          ctaText="Login"
          ctaHref="/"
          ctaVariant="primary"
          />
        <main className="container">
          {children}
        </main>
        <NewsletterFooter/>
      </ThemeProvider>
      </body>
    </html>
  );
}
