import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { MindwareIntro, Navigation } from '@/components'
import { ThemeProvider } from '@/components';

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mindware - Comércio & Serviços",
  description: "Generated by create next app",
};

const navigationItems = [
    { name: "Home", link: "/" },
    { name: "About", link: "/about" },
    { name: "Services", link: "/services" },
    { name: "Portfolio", link: "/portfolio" },
    { name: "Contact", link: "/contact" },
  ];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakarta.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <Navigation
        items={navigationItems}
        showCTA={true}
        ctaText="Sign Up"
        ctaHref="/register"
        ctaVariant="primary"
      />
        {/* <MindwareIntro/> */}
        <main className="container">
          {children}
        </main>
      </ThemeProvider>
      </body>
    </html>
  );
}
